#!/bin/bash

VERSION=`cat VERSION`
TAG=release-${VERSION}

echo "Preparing release with tag $TAG..."
git tag $TAG
if [ $? != 0 ]; then
  echo "This release already exists. You can not create another one. Aborting..."
  exit
fi

echo "Clean files from previous release..."
mkdir -p release
rm -f release/*

echo "Download artifacts from github..."
gh run download -n get-zap -D release/

echo "Use gh to create a release."
git push --tags upstream
gh release create $TAG --generate-notes release/*
